- INTEGRATING.md
- README.md
- lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py
- lib/charms/loki_k8s/v0/loki.py
- metadata.yaml
- src/charm.py
- src/loki_server.py
- tests/test_charm.py
- tests/test_consumer.py
- tests/test_provider.py
> Implement relation between loki and alertmanager

- .github/workflows/run_tests.yaml
- metadata.yaml
- tests/integration/helpers.py
- tests/integration/test_charm.py
- tests/integration/test_upgrade_charm.py
- tox.ini
Based on Leon's Alertmanaget tests
> Firsts Integration tests

- lib/charms/loki_k8s/v0/log_proxy.py
> FIX #38 _container.exec( -> _container.make_dir(

- src/charm.py
- src/loki_server.py
- tests/unit/test_charm.py
- tests/unit/test_loki_server.py
We were hardcoding Loki version because a Loki bug. This bug was solved.
> Fix loki_server version property

- lib/charms/loki_k8s/v0/loki_push_api.py
- LIBPATCH
- .pop() default value
> Minor fixes

- CONTRIBUTING.md
- INTEGRATING.md
- README.md
This PR improves charm's documentation.
- README.md
- CONTRIBUTING.md
- INTEGRATING.md
Besides it has the intention to produce a documentation example for other charms
> Improving charm's documentation

- lib/charms/loki_k8s/v0/loki_push_api.py
Change the inheritance of `LogProxyConsumer` so Alert Rules can
be pulled to the existing machinery.
Add docstrings for the `LogProxyConsumer` class explaining the
arguments and possible exceptions.
> LogProxyConsumer should inherit from `ConsumerBase`

- lib/charms/loki_k8s/v0/loki_push_api.py
This PR duplicates the prom equivalent introduced in https://github.com/canonical/prometheus-k8s-operator/pull/224
> load both .rule and .rules files

- lib/charms/loki_k8s/v0/loki_push_api.py
- tests/integration/helpers.py
- tests/integration/test_alert_rules.py
- tox.ini
> FIX #96 - Only the alert rules of the relations that are deleted are removed.

- lib/charms/loki_k8s/v0/loki_push_api.py
> fixed error with container name

- tests/sample_rule_files/free-standing/error/alert.rule
This simple PR adds an alert rule with syntax error for testing purposes
> Adding alert rule with a syntax error for testing

- lib/charms/loki_k8s/v0/loki_push_api.py
- tests/unit/test_log_proxy_consumer.py
Closes #109.
Rephrase error messages and consistently emit promtail digest error.
`tox -e unit`
Rephrase error messages and consistently emit promtail digest error.
Crossref: [OPENG-744](https://warthogs.atlassian.net/browse/OPENG-744)
> Fix multiple/no containers present error message

- lib/charms/loki_k8s/v0/loki_push_api.py
#118 
Add documentation.
None! Just give it a read.
Added documentation.
> Add section to the docs about topology labels

- tests/integration/helpers.py
- tests/integration/test_self_monitoring.py
- tox.ini
Integration tests for the recently added self monitoring.
Added integration tests
It tests itself...
-
> self monitoring integration tests

- lib/charms/observability_libs/v0/juju_topology.py
- lib/charms/observability_libs/v0/kubernetes_compute_resources_patch.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/traefik_k8s/v1/ingress_per_unit.py
- tests/unit/test_charm.py
`fetch-lib` to grab the race fix for `KubernetesResourcePatch`, and pull in others also.
`fetch-lib` to grab the race fix for `KubernetesResourcePatch`, and pull in others also.
> Update all client libraries

- lib/charms/loki_k8s/v0/loki_push_api.py
- pyproject.toml
Related to comments made in #214 after merge.
> fix typing issues

- CONTRIBUTING.md
- README.md
- tox.ini
> add badges to README.md

- lib/charms/loki_k8s/v0/loki_push_api.py
- src/charm.py
- tests/integration/helpers.py
- tests/integration/loki-tester/src/charm.py
- tests/unit/test_charm.py
- tests/unit/test_transform.py
The Loki ROCK, matching upstream, uses `/etc/loki/loki-local-config.yaml`, _not_ the hardcoded path currently used.
Update it so Loki passes CI (again)
> Point to the config file in the ROCK

- lib/charms/loki_k8s/v0/loki_push_api.py
- tests/unit/test_consumer.py
Without going as far as `RulesProvider` in `prometheus_scrape`, since we don't need to skip other data, add an optional arg to bypass appending Juju topology labels to alert rules.
Since `metadata` is still provided in the relation, the "other side" is able to establish an identifier for the filename anyway, and `apply_label_matchers` will effectively NOOP without labels, as there's nothing to inject into expressions.
See: [this cos-config issue](https://github.com/canonical/cos-configuration-k8s-operator/issues/44) for reference
Add an arg to skip topology label injection for Loki alert rules
> Add an arg to skip topology label injection for Loki alert rules

- src/grafana_dashboards/metrics-dashboard.json
Clean up the Loki dashboard a bit, removing non-standard plugins and such.
> clean up dashboard

- charmcraft.yaml
- lib/charms/observability_libs/v0/cert_handler.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- metadata.yaml
- pyproject.toml
- requirements.txt
- src/charm.py
- src/config_builder.py
- tests/unit/test_charm.py
This PR implements TLS as part of this tracking issue https://github.com/canonical/cos-lite-bundle/issues/75
1. Deploy Loki
2. Deploy `self-signed-certificates`
3. Deploy `prometheus-k8s`
4. Relate Loki to `self-signed-certificates` and `prometheus-k8s`
5. You can check HTTP endpoint in Prometheus:
> Implement TLS and enable it when a cert is available

- lib/charms/grafana_k8s/v0/grafana_source.py
- src/charm.py
This PR updates `source_url` for `GrafanaSourceProvider` when `cert_changed` event is emitted
> update source_url when server_cert_changed event is emitted

- lib/charms/grafana_k8s/v0/grafana_source.py
- src/charm.py
- tests/unit/test_charm.py
This PR fixes Loki configuration to use proper alertmanager scheme (HTTP or HTTPS)
> fix Alertmanager settings to use proper scheme

- src/charm.py
> update endpoint on cert changed

- actions.yaml
- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/observability_libs/v0/cert_handler.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/traefik_k8s/v1/ingress_per_unit.py
- src/charm.py
This PR fixes #298
`scrape_jobs()` refactored by making use of the port only if it's defined
> FIX on prometheus scrape url

- lib/charms/loki_k8s/v0/loki_push_api.py
Promtail can't push logs to loki when loki has TLS enables.
Conditionally add "insecure skip verify" to promtail config.
In tandem with:
- https://github.com/sed-i/flog-k8s-operator/pull/2
Before, this change, curling the loki endpoint gives an empty results:
```
$ curl -k https://10.1.166.70:3100/loki/api/v1/series
{"status":"success","data":[]}
```
With this change, the endpoint returns non empty results:
```
$ curl -k https://10.1.166.70:3100/loki/api/v1/series
{"status":"success","data":[{"juju_model_uuid":"6631cb63-cd13-4d80-8fcf-6191a60a5c9d","juju_model":"test","juju_charm":"flog-k8s","juju_application":"flog","job":"juju_test_6631cb63_flog","filename":"/bin/fake.log","juju_unit":"flog/0"}]}
```
Deploy the following bundle to confirm:
```yaml
applications:
ca: …
```
> [LogProxyConsumer] Add insecure_skip_verify arg

- lib/charms/loki_k8s/v1/loki_push_api.py
- lib/charms/tls_certificates_interface/v2/tls_certificates.py
- lib/charms/traefik_k8s/v1/ingress_per_unit.py
- tests/integration/conftest.py
- tests/integration/helpers.py
- tests/integration/log-forwarder-tester/charmcraft.yaml
- tests/integration/log-forwarder-tester/config.yaml
- tests/integration/log-forwarder-tester/lib/charms/observability_libs/v0/juju_topology.py
- tests/integration/log-forwarder-tester/metadata.yaml
- tests/integration/log-forwarder-tester/requirements.txt
- tests/integration/log-forwarder-tester/src/charm.py
- tests/integration/log-forwarder-tester/src/loki_alert_rules/alerting.rule
- tests/integration/test_log_forwarder.py
This PR fixes #358
Merge this after: 
- approving this one: https://github.com/canonical/cos-lib/pull/22
- updating cos-lib
> Observe Pebble Ready in LogForward

- lib/charms/loki_k8s/v0/loki_push_api.py
- lib/charms/loki_k8s/v1/loki_push_api.py
#331 added an import without adding PYDEPS.
This worked so far because it was included from somewhere else.
Add PYDEPS.
> Add cosl to PYDEPS

- src/charm.py
- tests/unit/test_charm.py
Some log lines are confusing.
Reword with some context.
Currently the `_check_alert_rules` method is very minimal. May want to refactor it and verify alerts by a different means.
> Improve some log messages

- lib/charms/loki_k8s/v0/charm_logging.py
- src/charm.py
we shouldn't warn as it's possibly a happy path
> Fix warning cert none charm logging

- src/grafana_dashboards/metrics-dashboard.json
Closes #435.
P.S.: The dashboard should be rewritten from scratch at some point.
- use `$__rate_interval` in the **Messages Input** panel
- mention that the **Index** row won't have any data (we could also remove it, but I went for minimal changes with the perspective of a rewrite)
- the `juju_application` and `juju_unit` variables now filter by `juju_charm=~"loki-k8s"`
> fix(dashboards): minor fixes

- lib/charms/loki_k8s/v1/loki_push_api.py
- tests/integration/test_log_forwarder.py
> `LogForwader` doesn't handle alert rules

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- lib/charms/prometheus_k8s/v0/prometheus_scrape.py
- lib/charms/tempo_coordinator_k8s/v0/charm_tracing.py
- lib/charms/tempo_coordinator_k8s/v0/tracing.py
- tests/unit/conftest.py
- tox.ini
Supersedes https://github.com/canonical/loki-k8s-operator/pull/480
> chore: update libraries and remove .charm_tracing_buffer

- README.md
Suggestions for what I think are typos or just a lack of clarity
If you approve this, please merge it as well as I probably wont come back here to check :)
> docs: nit changes to readme.md
