canonical/loki-k8s-operator

lib/charms/loki_k8s/v0/loki_push_api.py, tests/sample_rule_files/free-standing/alerting.rule, tests/sample_rule_files/free-standing/recording.rule, tests/sample_rule_files/with_topology/alerting.rule, tests/sample_rule_files/with_topology/alerting2.rule, tests/sample_rule_files/with_topology/recording.rule, tests/unit/test_consumer.py, tests/unit/test_provider.py
This PR adds the necessary functionality needed by [lma-rules-operator](https://github.com/canonical/lma-rules-operator) to forward free standing rules.
Similar changes have been [made to prometheus-operator](https://github.com/canonical/prometheus-operator/pull/149).
=> foundations for free-standing rules

lib/charms/loki_k8s/v0/loki_push_api.py, src/charm.py, tox.ini
This PR proposes to:
1. Provide the minimal loki config explicitly, instead of pulling the one that is already in the container and updating it.
2. Have the rules dir passed to loki lib from the charm.
3. Add the "fake" subdir to the rules dir ([ref](https://grafana.com/docs/loki/latest/operations/storage/filesystem/)).
4. Update `_stored.config` only after `push` succeeds.
=> push full config instead of pulling and updating

lib/charms/loki_k8s/v0/loki_push_api.py, metadata.yaml, tests/unit/test_charm.py, tests/unit/test_provider.py
This is a bugfix + upkeep PR:
- bugfix: add missing `.identifier` to rules filename. Before this change, filename was e.g. `JujuTopology(model='lma', model_uuid='ea95a2e', application='lma-rules-k8s', charm_name='lma-rules-k8s')_rel_6_alert.rules`. Bug introduced in my previous PR.
- add version tag to loki image
- create "tenant" dir and patch unittests that end up calling pebble's make_dir, until https://github.com/canonical/operator/pull/645 is merged.
=> fix rules file path + upkeep

lib/charms/loki_k8s/v0/log_proxy.py, metadata.yaml, tests/unit/test_log_proxy_consumer.py
When a relation is established between the consumer and the provider side, the library checks whether Promtail binary is attached as a resource in the consumer side or not.
If it's attached uses that binary, if not checks if it's already downloaded and use that downloaded binary. If it's not downloaded, downloads it.
=> Promtail binary is obtained from an attached resource or download it

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_consumer.py
Before this PR we were setting (in the library) `BlockedStatus` in the unit if there was an error with alert rules.
Now whether alert rules files does not contain the keys `alert` or `expr` or
there is no alert rules file in `alert_rules_path` a `loki_push_api_alert_rules_error` event
is emitted.
For this, in this PR we:
- created a custom event: `LokiPushApiAlertRulesError`
- refactor some methods
=> Emit custom event if there is an error with alert rules.

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_consumer.py, tests/unit/test_provider.py
1) Send the endpoint URL over application databags rather than unit (which will not work with distributed Loki)
2) Correctly handle multiple instances of the relation, avoiding concurrent overriding of the endpoint data in the Consumer storage
3) Support the upgrade of charms that include the LokiPushApiConsumer
4) Make the relation databag for the Loki endpoint extensible (using a dict rather than just a string to communicate the URL)
=> Fix various issues with the Loki Push API library

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/helpers.py, tests/unit/test_consumer.py, tox.ini
This PR adds a private method for refreshing (re-initializing) relation data for alerts.
This is needed for cos-config to be able to refresh alerts when alerts show up on disk after the last hook fired.
cf. https://github.com/canonical/prometheus-k8s-operator/pull/208, https://github.com/canonical/grafana-k8s-operator/pull/53
=> add private method to reinitialize alerts

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_consumer.py
This PR brings in the AlertRules class from prom to loki.
This allows loki to read alerts in both formats - official and short-form.
The diff looks big because the branch is based on #76. When #76 merges, the diff will become smaller.
This change is (urgently) needed by https://github.com/canonical/cos-configuration-k8s-operator/pull/6
=> Streamline AlertRules class from prometheus

lib/charms/grafana_k8s/v0/grafana_source.py, lib/charms/loki_k8s/v0/loki_push_api.py, pyproject.toml, src/charm.py, tests/unit/test_consumer.py, tests/unit/test_log_proxy_consumer.py
Send events like LokiPushApi already does so the UX is the same.
Instead of raising exceptions for everything in the LogProxy code, forcing consumers to catch them to set state, fire back an event if something happens with the Promtail Binary.
Only send a new `ContainerNotFound` Exception if the container name is unset or ambiguous enough that we can't suss one out.
Add a bunch of type hints.
Update tests.
Closes #70 
Closes #69 
Really depends on #67, but the changes on top of that are reasonably small
=> Use events for LogProxy, get rid of PromtailError as Exception

lib/charms/grafana_k8s/v0/grafana_source.py
In some cases `.get_binding.network_address` may return `None`, which is directly interpolated as a string, and may cause datasources in Grafana to have an invalid source.
Worse, a rapid break/join of the relation when this is set appears to have put Grafana's embedded database into a bad state. Can't reproduce, but better safe than sorry.
=> Use an updated 'grafana_source' library to fix a rare race in the unit IP being set

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_log_proxy_consumer.py, tests/unit/test_provider.py
Instead of using its own, merge together the last of the changes
from the PR storm.
The one remaining difference is that Loki uses `metadata` as a relation key instead of `scrape_metadata`, which makes sense for naming but must be kept in mind instead of blindly copying and pasting it in the future.
=> Finally, bring loki_push_api in sync with the new topology instead of using its own

lib/charms/loki_k8s/v0/loki_push_api.py
Since Loki and Prom both use `container.push()` for rules, which
blindly converts any string with '/' in it to a directory tree,
we may accidentally write nested paths when we don't intend to.
Replace path separators.
=> Replace '/' with '_' in topology.identifier

lib/charms/loki_k8s/v0/loki_push_api.py, src/charm.py, tests/integration/test_alert_rules.py, tests/unit/test_provider.py
This PR introduces changes to `LokiPushApiProvider`
- Once a relation is established and alert rules are sent through relation data, the object will check alert rules by querying Loki API. If there are no errors a `loki_push_api_alert_rules_ok` event is emitted. In the other hand if there are errors with alert rules, `loki_push_api_alert_rules_error` event is emitted.
- Loki charm now observes these new events and sets unit status accordingly.
- Refactor in `_remove_alert_rules_files()`. Now we delete one by one alert rule files instead of removing the entire directory.
=> FIX #91 - Loki push_api lib should validate alert rules

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_consumer.py, tox.ini
`yaml.safe_load` may return a None. This PR makes sure this case is correctly handled.
Resolves #98.
Crossref: OPENG-649
=> Correctly treat empty rule files

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_consumer.py
This makes it so that all units will trigger alerts instead of just the leader.
When using the loki_push_api library, "juju_unit" is added to the alert rules. This causes the rule to only apply to the leader and not to the other unit.
I used the updated JujuTopology class copied from prometheus_scrape with a minor modification to make it work in loki_push_api. This removes the "juju_unit" key from the alert rules.
Similar to [this PR](https://github.com/canonical/prometheus-k8s-operator/pull/239)
Deploy a charm that has loki alert rules defined. (cassandra-k8s from the "update_for_cos" branch has this)
Relate to loki-k8s
Use `juju show-unit` and `curl http://address/loki/api/v1/rules` to verify the labels and expression are both correct.
* Update alert rules to not use "juju_unit" as part …
=> Update alert rules to not use "juju_unit" as part of the topology

.github/workflows/build-promtail-release.yaml
Reduce download size of Promtail binaries for the LogProxyConsumer charms.
Compress the binaries with gz upon the publication of the GitHub release.
It is a tragedy that we cannot have GitHub compress the content for us based on MIME types and Accept headers.
Check https://github.com/mmanciop/loki-operator/releases/tag/promtail-v2.4.2
=> Compress promtail binaries for release with gzip

.github/workflows/pull-request.yaml, lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_consumer.py, tests/unit/test_provider.py
Use of a common handler for virtually all relation events meant that there was a somewhat excessive amount of chatter between provider/consumer.
Move the relevant data/updates to the events they "belong to".
Closes #140 
Closes #65 
Set relatively static data (alert rules, promtail_binary_url,
topology/metadata) in relation_joined. Fire events on
relation-changed so endpoints are still updated.
Streamline event handling.
Remove more mocking.
Make the state-dependent unit tests for reloading alert rules
explicitly ignore sorting. Unittests should:
* Be in a `unittest.TestSuite` if ordering matters
* Not be dependent on the order of previous tests, since `unittest` sorts (by default) using `dir()` and alphabetic sorting. Making functions "digestible" at the cost of predictability is not …
=> No common exit hook in lib

.github/workflows/pull-request.yaml, lib/charms/loki_k8s/v0/loki_push_api.py, src/charm.py, tests/unit/helpers.py, tests/unit/test_charm.py
Closes #75 
Write unit tests to address scenario.
`tox -e unit -- -k TestDelayedPebbleReady`
Add unit tests for startup event ordering.
Crossref: [OPENG-402](https://warthogs.atlassian.net/browse/OPENG-402)
=> Add unit tests for startup events ordering

.github/workflows/pull-request.yaml, lib/charms/loki_k8s/v0/loki_push_api.py, src/charm.py, tests/integration/helpers.py, tests/integration/test_alert_rules_load.py, tests/integration/test_charm.py, tests/integration/test_kubectl_delete.py, tests/integration/test_multiple_rule_providing_apps.py, tests/integration/test_upgrade_charm.py, tests/integration/test_upgrade_charm_retains_alerts.py, tests/unit/test_charm.py
Previously, a failure in `_check_alert_rules` followed by almost
any other event could cause the state to be reset back to
`ActiveStatus`, since typechecking the event would _probably_ not
be correct.
Closes #113
Kill the "common exit hook" in `charm.py`, and move explicit state
checks for alerting events to the appropriate method
Updated even more unit tests.
Accurately flag statuses from checking alert rules
=> Accurately flag statuses from checking alert rules

.github/workflows/pull-request.yaml, lib/charms/loki_k8s/v0/loki_push_api.py, tests/integration/helpers.py, tests/integration/test_alert_rules_load.py, tests/integration/test_charm.py, tests/integration/test_kubectl_delete.py, tests/integration/test_multiple_rule_providing_apps.py, tests/integration/test_upgrade_charm.py, tests/integration/test_upgrade_charm_retains_alerts.py, tests/unit/test_provider.py
`loki_push_api` littered the logs with warning messages on every invocation if no alert rules were present in a relation, even if they were no included in the charm at all.
Closes #128
Closes #53
Closes #106
Closes #142 
Emit messages in `LogProxyConsumer` and `LokiPushApi*` if we
cannot connect to the container.
Stop using `logger.warning` for messages when the alert rules path
doesn't exist -- default constructor args should mean endless
warnings.
Prune more dead code in `RelationManagerBase`, the methods of which
are never called anywhere.
Condense the alert rule generation/removal/updates into a single
method which tries to generate the alert rules _prior_ to removing
everything.
Even running the unit tests is sufficient before and after this change.
Prune log messages from …
=> Stop spamming warning logs, prune and streamline code

lib/charms/loki_k8s/v0/loki_push_api.py, tests/unit/test_log_proxy_consumer.py
`LogProxyConsumer` currently only supports AMD64 architectures. Hence it can not install and use Promtail on other architectures such as ARM64. The purpose of this PR is to support both AMD64 and ARM64 architectures and ensure additional architectures can be easily added in the future.
The following changes were made as part of this refactor.
- The relation data structure with promtail information set by LokiPushApiProvider has been extended so that it includes
+ information for multiple architectures
+ URL and filename of Promtail for each architecture
+ sha256 sum of Promtail zip for each architecture
+ sha256 sum of Promtail binary for each architecture
- All hardcoding of filename and paths for Promtail binaries were removed. The filenames are extracted from relation data provided by …
=> Support both AMD64 and ARM64 Promtail binary URLs

.gitignore, .jujuignore, charmcraft.yaml, lib/charms/alertmanager_k8s/v0/alertmanager_dispatch.py, lib/charms/grafana_k8s/v0/grafana_source.py, lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/observability_libs/v0/juju_topology.py, lib/charms/traefik_k8s/v0/ingress_per_unit.py, tests/integration/log-proxy-tester/lib/charms/observability_libs/v0/juju_topology.py, tests/integration/loki-tester/lib/charms/observability_libs/v0/juju_topology.py, tests/integration/loki-tester/src/charm.py, tests/unit/test_charm.py, tests/unit/test_consumer.py, tests/unit/test_log_proxy_consumer.py, tests/unit/test_provider.py, tests/unit/test_transform.py, tox.ini
Kind of a lot.
A mechanism was needed to validate alert rules _before_ Loki died if they were loaded, and `JujuTopology` is now in `observability-libs`, so removal of the custom code was slated.
Add `cos-tool`, which does what `promql-transform` did for PromQL label tranformation, plus also handlingalert rule validation. Add tests for all of that, and an event fired back if an alert rule is invalid, which is then excluded from being loaded into Prometheus
Replace the "custom" `JujuTopology` with the one from `observability-libs`, which works well, but required a really annoying amount of updates to tests, especially unit tests to avoid `InvalidUUID` exceptions blowing them up.
Test, run, be joyful.
Use `JujuTopology` from observability-libs, validate alert rules, inject label matchers …
=> Use cos-tool to transform/validate, use JujuTopology from observability libs

lib/charms/grafana_k8s/v0/grafana_dashboard.py, metadata.yaml, src/charm.py, src/grafana_dashboards/metrics-dashboard.json, tests/integration/test_upgrade_charm.py
Create a dashboard for Loki metrics.
Add dashboard using the grafana_dashboard library.
You need to relate this to a Grafana charm built from the dashboard-parse-inputs branch (Currently in review)
Added metrics dashboard to Loki-k8s
=> Add metrics dashboard

src/charm.py, tox.ini
Ingress is not set correctly for loki:
- The loki config file is not use `external_url`.
- After `remove-relation`, the loki ingress is still the traefik address, i.e. it is not being reset.
- Observe `ingress_per_unit.on.revoked_for_unit`
- Set `ruler.external_url` in config file
Load tests.
- Deploy and relate loki and traefik.
- Try to curl `loki/metrics` with/without ingress.
=> Fix ingress

src/grafana_dashboards/metrics-dashboard.json
Currently, the Loki Dashboard is named "Loki2.0 Global Metrics", which harmonizes badly with our other dashboards.
Rename to "Loki Operator Overview", making it match Prometheus
N/A
N/A
Rename the built-in Loki dashboard
=> Rename self-monitoring dashboard

src/charm.py
In case of a host restart, it's possible that no alert events will actually be fired, as there are no relation changes.
Pre-emptively attempt to fetch and generate alert rules `on_loki_pebble_ready`. Even in the case of empty alerts, this is harmless.
Deploy Loki. Relate something with alerts. Reboot the host. Ensure they are still present.
Refresh alert rules on pebble ready to account for potential pod churn
=> Refresh alert rules on pebble ready to account for potential pod churn

src/charm.py
This PR fixes #219.
We added a `try...except` block to catch `ChangeError` in case we try to restart the container while it is being destroyed.
Read #219
Read #219
=> catch ChangeError when restating the container

.github/workflows/build-promtail-release.yaml, lib/charms/loki_k8s/v0/loki_push_api.py, tox.ini
Previously, an explicit matcher (`job=".+"`) was used due to a typo, rather than a fuzzy (`job=~".+"`) matcher. 
Closes #228 
Closes #224
Fix the typo.
Also, bump the golang version for promtail releases.
Fix the `job=...` expression for alert rules
=> Fix the `job=...` expression for alert rules

pyproject.toml, tests/unit/test_charm.py
Previously these tests had the following error when trying to use ops 2.0.0rc2:
```
Traceback (most recent call last):
File "/home/ben/w/loki-k8s-operator/tests/unit/test_charm.py", line 377, in setUp
self.harness.begin_with_initial_hooks()
File "/home/ben/w/loki-k8s-operator/.tox/unit/lib/python3.10/site-packages/ops/testing.py", line 353, in begin_with_initial_hooks
self.container_pebble_ready(container_name)
...
NotImplementedError: <bound method _TestingPebbleClient.exec of <ops.testing._TestingPebbleClient object at 0x7f562f1207c0>>
```
It was happening because of the changes to begin_with_initial_hooks() now triggering pebble-ready. Use begin() instead here, and manually emit config-changed so the charm status is set to WaitingStatus.
Also remove the warning about the unexpected …
=> Fix TestDelayedPebbleReady pebble-ready issues with ops 2.0.0rc2

.github/workflows/build-promtail-release.yaml
Also, bump golang to `1.19`.
`ubuntu-latest` is now 22.04, and is not ABI compatible with the tester images being used, so an appropriate version of `glibc` can't be found by the linker.
We could actually step around this and statically link `glibc` in also, but it would require modifying the `Makefile` for `grafana/loki` as part of an action, because it doesn't look for any meaningful env vars we could substitute.
With a `grafana-agent` machine snap/charm, do we actually have a need for an in-container rebuilt promtail which can read journalctl?
For that matter, is there a reason we're rebuilding this at all instead of grabbing the prebuilt binary from upstream? @simskij ?
=> Build against 20.04 and a compatible version of glibc

lib/charms/loki_k8s/v0/loki_push_api.py
Make `loki_push_api` use the same logic as `prometheus_remote_write`  for alerts -- one which prioritizes the labels on alerts (if present) over metadata, since providing charms who use AlertRules will have them injected, and we shouldn't clobber them.
prometheus_remote_write already does this, but `loki_push_api` would otherwise overwrite forwarded rules with possibly misleading/meaningless data.
=> Sync up the `alerts` method in the libraries

lib/charms/loki_k8s/v0/loki_push_api.py
Resolves #256.
As suggested in the issue, the `update_endpoint()` function is designed to only handle one relation (see [get_relation() docs](https://ops.readthedocs.io/en/latest/index.html?highlight=get_relation#ops.model.Model.get_relation)).
Change `update_endpoint()` to update all relations if a specific one isn't specified.
* pack and deploy Loki from my PR
* deploy some charms that support the `loki_push_api` interface (`traefik:logging` is a good example)
* relate Loki to multiple charms over `loki_push_api`
* relate Loki to Traefik over `ingress` and verify that no ERROR appears in `juju debug-log`
Change `update_endpoint()` to update all relations if a specific one isn't specified.
=> fix handling of multiple loki_push_api relations

metadata.yaml
We are currently running Loki using the upstream OCI image.
We are now building our own ROCKs for the observability stack. We should also make sure we're using them so that effort is not in vain.
- Deploy the charm with the new resource
- Verify functionality is still there
Switch from upstream OCI image to ROCK
=> Switch Loki to use the ROCK on ghcr.io

lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, tests/unit/test_log_proxy_consumer.py
If a user mistakenly passed an str instead of a list for the `log_files` arg, the response is too silent and too late.
Raise on type mismatch for `log_files`.
Fixes #226.
[Temptation](https://typeguard.readthedocs.io/en/latest/) was mild.
Afaict, utest provides sufficient coverage.
Type check the log_files arg.
=> Type check the `log_files` arg

lib/charms/loki_k8s/v0/loki_push_api.py, pyproject.toml, src/charm.py, src/loki_server.py, tests/integration/test_applications_send_logs.py, tests/unit/test_charm.py, tests/unit/test_log_proxy_consumer.py, tests/unit/test_loki_server.py, tests/unit/test_transform.py, tox.ini
The **flake8** plugins we use are re-implemented in **ruff**, which is why they have been removed from the dependencies.
**isort** is enabled (and used when formatting) through the `I001` rule.
The "exclude list" has been updated to omit folders that **ruff** excludes by default.
Everything else is the same, the only difference being one new rule being ignored (which wasn't checked before anyway):
* `RET504: Unnecessary variable assignment before return statement`, which we do everywhere as it increases readability.
=> use ruff instead of flake8

lib/charms/grafana_k8s/v0/grafana_dashboard.py, lib/charms/prometheus_k8s/v0/prometheus_scrape.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, lib/charms/traefik_k8s/v1/ingress_per_unit.py, src/charm.py, tox.ini
This PR fixes #305 which are actually 2 bugs:
- Loki's scrape target built using Ingress IP rather than fqdn.
- Certificate is issued for `loki-0` instead of fqdn.
- Now Prometheus scrape target is built using fqdn
- Certificate is requested for fqdn instead of `APP_NAME-UNIT`
This PR is part of the [TLS overlay](https://github.com/canonical/cos-lite-bundle/pull/80)
1. Deploy COS-Lite using the TLS overlay:
```yaml
applications:
ca:
charm: self-signed-certificates
channel: edge
scale: 1
options:
ca-common-name: ca.demo.local
external-ca:
charm: self-signed-certificates
channel: edge
scale: 1
options:
ca-common-name: external.demo.ca
relations:
- [external-ca, traefik:certificates]
- [ca, traefik:receive-ca-cert]
- [ca, alertmanager:certificates]
- [ca, prometheus:certificates]
- [ca, …
```
=> FIX scrape target and certificate created for loki

PROMTAIL_RELEASES.md, lib/charms/loki_k8s/v1/loki_push_api.py, lib/charms/observability_libs/v0/cert_handler.py, lib/charms/tls_certificates_interface/v2/tls_certificates.py, tests/integration/conftest.py, tests/integration/helpers.py, tests/integration/log-proxy-tester/metadata.yaml, tests/integration/log-proxy-tester/src/charm.py, tests/integration/loki-tester/src/charm.py, tests/integration/test_log_proxy.py, tests/integration/test_log_proxy_alert_rules.py, tests/integration/test_log_proxy_send_logs.py
This PR fixes #307
A new version of loki_push_api lib
Before this PR, it was not possible to send logs from more than one container of the charm.
1. Pack the `log-proxy-tester`
2. Deploy this bundle:
```yaml
applications:
loki:
charm: loki-k8s
channel: edge
revision: 101
resources:
loki-image: 84
scale: 1
constraints: arch=amd64
storage:
active-index-directory: kubernetes,1,1024M
loki-chunks: kubernetes,1,1024M
trust: true
tester:
charm: ./tests/integration/log-proxy-tester/log-proxy-tester_ubuntu-20.04-amd64.charm
scale: 1
constraints: arch=amd64
resources:
workload-image: ghcr.io/sed-i/flog:latest
relations:
- - tester:log-proxy
- loki:logging
```
3. Check that there are 2 series in Loki:
```shell
$ curl -s http://10.1.38.92:3100/loki/api/v1/series | jq
{
"status": …
```
=> new loki_push_api lib version

.gitignore, .jujuignore, config.yaml, doc/adr/2023-11-21 config options for rate limits.md, doc/adr/README.md, src/charm.py, src/config_builder.py
The charm does not expose config options for ingestion rate limits.
Add config options for ingestion rate limits.
Fixes #323.
- https://github.com/canonical/cos-lite-bundle/pull/84
=> Add config options for ingestion rate limits

src/config_builder.py
Following up on #324, as the problem still persists.
- Getting HTTP codes 429 and others throughout the load test.
- Loki logs `2023-11-22T20:28:31.034Z [loki] level=warn ts=2023-11-22T20:28:30.939304741Z caller=cache.go:114 msg="fifocache config is deprecated. use embedded-cache instead"`
- Enable embedded-cache.
- Additional tweaks, per refs inline.
With this change, at high load (`increase(loki_distributor_lines_received_total[1m])` of up to 320,000), all of the following issues are now gone:
- 429 / GET / loki_api_v1_query_range
- 499 / GET / loki_api_v1_query_range
- 500 / GET / loki_api_v1_query_range
- 503 / GET / ready
- 500 / POST / loki_api_v1_push
- cancel / gRPC / /logproto.Querier/Query
- cancel / gRPC / /schedulerpb.SchedulerForQuerier/QuerierLoop
Fixes #283.
- …
=> Modify loki config to address HTTP 429 code (too many reqs)

lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/loki_k8s/v1/loki_push_api.py, requirements.txt, tests/integration/log-proxy-tester/requirements.txt, tests/integration/loki-tester/requirements.txt, tests/integration/loki-tester/src/charm.py, tests/unit/test_consumer.py, tox.ini
Closes #310.
Import `JujuTopology` from **cosl** instead of using the deprecated `charms.observability_libs.v0.juju_topology`.
=> use cosl for JujuTopology

lib/charms/loki_k8s/v1/loki_push_api.py
Adjust `loki_push_api` docs to use `v1` instead of `v0` where needed.
Fixes #337.
=> Update v0 to v1 in loki_push_api docs

charmcraft.yaml, lib/charms/tempo_k8s/v1/charm_tracing.py, lib/charms/tempo_k8s/v1/tracing.py, metadata.yaml, src/charm.py, tests/unit/test_charm.py, tox.ini
Add charm_tracing support to loki charm using autoinstrumentation.
Run the following bundle:
```
applications:
alertmanager:
charm: alertmanager-k8s
channel: stable
revision: 96
series: focal
resources:
alertmanager-image: 84
scale: 1
constraints: arch=amd64
storage:
data: kubernetes,1,1024M
trust: true
catalogue:
charm: catalogue-k8s
channel: stable
revision: 33
series: focal
resources:
catalogue-image: 32
scale: 1
options:
description: "Canonical Observability Stack Lite, or COS Lite, is a light-weight,
highly-integrated, \nJuju-based observability suite running on Kubernetes.\n"
tagline: Model-driven Observability Stack deployed with a single command.
title: Canonical Observability Stack
constraints: arch=amd64
trust: true
grafana:
charm: grafana-k8s
channel: stable …
```
=> Add charm tracing

metadata.yaml, tests/integration/test_alert_rules_are_forwarded.py
Users are able to deploy on juju 2.9.
Add assumes statement for `juju >= 3.0.3`.
=> Add assumes statement for `juju >= 3.0.3`

.github/workflows/build-promtail-release.yaml
To make `loki_push_api.py` work with arm64, we need to also have a promtail binary built for that arch.
Build it! 🔥
=> Build promtail for arm64

lib/charms/loki_k8s/v1/loki_push_api.py
Alert labels are being overwritten, when they already exist.
This is a problem for deployments with grafana-agent, such as:
```mermaid
graph LR
some-charm ---|logging| grafana-agent ---|logging| loki
```
Before this change, the alert labels of `some-charm` would be set to grafana-agent's topology.
Only insert labels that do not already exist. This is exactly what we're [doing in cos-lib](https://github.com/canonical/cos-lib/blob/486945531c3a95253c2ee3886204071b176e7841/src/cosl/rules.py#L298).
(In a different PR, we should refactor loki_push_api to use cos-lib.)
Addresses https://github.com/canonical/grafana-agent-k8s-operator/issues/275.
This PR is in tandem with:
- https://github.com/canonical/grafana-agent-k8s-operator/pull/277
Deploy this bundle:
```yaml …
```
=> Only insert labels that do not already exist

lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/loki_k8s/v1/loki_push_api.py
[In the last episode](https://github.com/canonical/loki-k8s-operator/pull/352) we fixed the logic around setting the keys of the input `proxies` dict to the ProxyHandler. In this one, our heroes learn about a tragic mistake they made during their hard fought battle: [the keys should be the protocol names only, without the `_proxy` suffix](https://docs.python.org/3/library/urllib.request.html#urllib.request.ProxyHandler).
With this new knowledge in hand, the happy gathering decided that all this was a learning experience and as Nicolas Boileau wrote in "L'Art poétique":
> Hâtez-vous lentement, et, sans perdre courage,
Vingt fois sur le métier remettez votre ouvrage
The mistake was promptly fixed and life was beautiful.
The end.
=> Fix keys in the proxies input dict to only be protocol names

lib/charms/loki_k8s/v1/loki_push_api.py
When promtail download fails due to proxy not being set up, the charm [goes into error state](https://bugs.launchpad.net/juju/+bug/2056193):
```
unit-httprequest-lego-provider-0: 14:38:24 ERROR unit.httprequest-lego-provider/0.juju-log Uncaught exception while in charm code:
Traceback (most recent call last):
File "/usr/lib/python3.10/urllib/request.py", line 1348, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
File "/usr/lib/python3.10/http/client.py", line 1283, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/lib/python3.10/http/client.py", line 1329, in _send_request
self.endheaders(body, encode_chunked=encode_chunked)
File "/usr/lib/python3.10/http/client.py", line 1278, in endheaders
self._send_output(message_body, …
```
=> Catch URLError instead of HTTPError

src/charm.py
Fixes https://github.com/canonical/loki-k8s-operator/issues/360 
SSL certificate verification failures can occur intermittently when [this file](https://github.com/canonical/loki-k8s-operator/blob/5f8c4b47ca302029ea39f3a9d7401e45c703e215/src/charm.py#L109) isn't present, leading to errors in connecting to the Loki API.
The solution involves implementing a guard mechanism to handle the missing certificates, This will prevent SSL certificate verification errors like "certificate verify failed: unable to get local issuer certificate".
1. Deploy cos-lite with the `tls-overlay`
2. Deploy `grafana-agent` and relate to a couple of charms that can push logs to Loki
3. Confirm that Loki is up and logs are being cascaded normally
=> Enhance SSL Certificate Handling

lib/charms/observability_libs/v1/cert_handler.py, src/charm.py, tests/unit/test_charm.py
Use `ops.Unit.open_port` for the port to show up in Juju status.
Due to a Juju bug, it might not show up there yet; use `juju exec <unit> -- opened-ports` to verify.
This PR also does `charmcraft fetch-lib` and manually updates the `cert_handler` lib to v1.
```
charmcraft pack
juju deploy ./loki-k8s_ubuntu-20.04-amd64.charm loki
juju exec --unit loki/0 -- opened-ports
```
=> add open port support

lib/charms/loki_k8s/v1/loki_push_api.py
We need to build grafana-agent-k8s for ARM; to do so, the ARM promtail binary needs to be downloaded when deploying on that architecture.
Download the ARM binary when the architecture is **arm64**.
Please download the promtail files yourself from [here (v2.9.7)](https://github.com/canonical/loki-k8s-operator/releases/tag/promtail-v2.9.7) and run `sha256sum` on both the zip and the binary, to make sure the ones I pasted are correct.
=> add support for promtail arm binary

lib/charms/tempo_k8s/v2/tracing.py, src/charm.py
Fixes #398
ca cert is pushed into charm container, so pass ca cert path to trace_charm decorator to use that for tls communication with tempo
1- Depends on https://github.com/canonical/tempo-k8s-operator/pull/98
2- Assumes loki and tempo have tls enabled 
3- Assumes CA of loki is the same for the one used by tempo's cert
=> charm tracing fails over tls

metadata.yaml, src/charm.py, src/config_builder.py, tests/integration/test_boltdb_v11_to_tsdb_v12_migration.py, tox.ini
Fixes #362 & #380
To avoid this becoming a breaking change in loki a few workarounds were implemented
1. TSDB data will live inside the active-index-directory originally created to accommodate boltdb, this is because adding a new PVC for it might disrupt the upgrade path as juju doesn't currently support this, this adjustment won't lead to storage overload, as all chunks, regardless of their schema, will still be directed to `/loki/chunks`
```
ERROR Juju on containers does not support updating storage on a statefulset.
The new charm's metadata contains updated storage declarations.
You'll need to deploy a new charm rather than upgrading if you need this change.
```
2. V12 schema migration date (The date for when loki will actually start to write logs in v12) will be set dynamically, with …
=> Adding TSBD storage to Loki and switching to v12 schema

lib/charms/loki_k8s/v0/loki_push_api.py, lib/charms/loki_k8s/v1/loki_push_api.py
We have an external dependency on promtail, which the charm lib (LogProxyConsumer) attempts to download from a hard-coded URL. This dependency is inconvenient to work around with in air-gapped environments.
Encourage users to migrate to LogForwarder by deprecating LogProxyConsumer.
1. LogProxyConsumer will be omitted from v2 of loki_push_api, but v0 and v1 are still available. Users who are happy with having the promtail dependency, can keep using it without change, and future changes to the loki lib won't break backwards compatibility as far as it comes to promtail.
1. No deprecation warnings are added in this PR, to avoid unnecessary (and inaccurate) messaging.
Closes https://github.com/canonical/grafana-agent-k8s-operator/issues/300.
- Pebble log forwarding support was added in Juju …
=> Add deprecation warning for LogProxyConsumer

src/charm.py
Loki's schema config `from` field uses dates in UTC to define what schema is applicable when.  Previously, this charm wrote the date in local time, which will lead to an inconsistency for a few hours (see https://grafana.com/docs/loki/latest/operations/storage/schema/#changing-the-schema).  This change addresses the issue, always using UTC time
=> fix: use UTC time in loki schema definition

src/charm.py
- Controller storage is unreliable: in a model migration we once saw `ops.storage.NoSnapshotError: no snapshot data found for LokiOperatorCharm/LokiPushApiProvider[logging]/on/loki_push_api_alert_rules_changed[250784] object`, which broke the upgrade.
- Controller storage is [deprecated in ops](https://github.com/canonical/operator/pull/882).
Stop using controller storage.
=> Stop using controller storage

lib/charms/loki_k8s/v1/loki_push_api.py, src/charm.py, tests/integration/log-forwarder-tester/charmcraft.yaml, tests/integration/log-proxy-tester/charmcraft.yaml, tests/integration/loki-tester/charmcraft.yaml, tests/unit/helpers.py, tox.ini
This PR add some missing `can_connect()` guards in loki_push_api lib, and improves exception handling in Loki charm.
See #390
- Run the test suite (unit, scenario, integration) and verify everything is green.
- Alternatively you can manually:
- `juju add-model apps`
- `juju deploy grafana-agent-k8s agent --channel latest/edge`
- `juju deploy sdcore-udr-k8s --channel 1.5/edge`
- Copy the new version of the lib into the sdcore-udr-k8s repo
- Sync repo with running charm: `jhack utils sync sdcore-udr-k8s/0`
- Relate both charms: `juju relate sdcore-udr-k8s:logging agent:logging-provider`
- Check there are no errors like [these ones ](https://github.com/canonical/loki-k8s-operator/issues/390) in juju debug-log like
=> Improve exceptions handling and add can_connect guards

lib/charms/observability_libs/v0/kubernetes_compute_resources_patch.py, lib/charms/observability_libs/v1/cert_handler.py, lib/charms/tempo_k8s/v1/charm_tracing.py, lib/charms/tls_certificates_interface/v3/tls_certificates.py, src/charm.py, src/config_builder.py, tests/integration/test_boltdb_v11_to_tsdb_v12_migration.py, tests/scenario/conftest.py, tests/unit/test_charm.py
In order to avoid [high cardinality in Loki](https://discourse.charmhub.io/t/solving-high-cardinality-labels-in-loki/15426) this PR enables `structured_metadata`
Partially solves https://github.com/canonical/loki-k8s-operator/issues/439 
This PR goes in tandem with: https://github.com/canonical/grafana-agent-operator/pull/180
Run integration tests
Now the default schema version is `v13`
=> Enable structured_metadata

lib/charms/tempo_k8s/v2/tracing.py, src/charm.py
Now we use loki_push_api v1.... 
While working on https://github.com/canonical/loki-k8s-operator/pull/455 and https://github.com/canonical/grafana-agent-operator/pull/185 I've found that we were using v0 of the lib
=> use loki_push_api v1

charmcraft.yaml, src/grafana_dashboards/metrics-dashboard.json
Closes #444.
The dashboard had some broken panel. I refreshed it based on the actual metrics exposed by Loki, while keeping it relatively similar to the original UI.
(drive-by: add `pydantic-core` to binary packages to reduce packing times and not require `rustc` and `cargo`)
<details><summary>Screenshots</summary>
<h3>Overview</h3>
<h3>Read Operations</h3>
<h3>Write Operations</h3>
<h3>Write Ahead Log (WAL)</h3>
<h3>Compaction and Retention</h3>
</details> 
Pack, deploy, relate to Grafana/Prometheus, and look at the dashboard!
The dashboard has the same title/uid but I increased the revision; this will make it so this dashboard replaces the old one seamlessly :)
=> fix: correct dashboard panels and improve them

config.yaml
This PR updates the `retention-period` config description to provide more detailed information about the default behavior and its relation to the `compactor.retention_enabled` setting. No functional changes.
=> Provide a more detailed description for retention-period config

config.yaml, requirements.txt, src/charm.py, src/config_builder.py, tests/scenario/conftest.py, tests/scenario/test_charm_logging.py, tests/scenario/test_config_reporting_enabled.py, tests/unit/test_charm.py, tests/unit/test_provider.py, tox.ini
Some users do not want to send anonymous usage statistics to `stats.grafana.org`. For example, in an air-gapped environment this may cause excess logs due to the endpoint being unreachable.
1. Adding a config option
Add a juju config option to the loki charm. By default the config will send usage statistics and will not write to the config file. Only if the `reporting-enabled` option is set to `false`, then we write to the [analytics block](https://grafana.com/docs/loki/latest/configure/#analytics) with `reporting_enabled=false` 
2. Add and fix tests
In an attempt to add scenario tests for testing this config option, the pin for ops=2.16 was removed and technical debt was removed to be compatible with the new ops.testing Scenario 7 syntax.
Since we want to contribute to upstream …
=> feat: disable-reporting juju config option

metadata.yaml, src/charm.py, tests/integration/helpers.py, tests/integration/test_workload_tracing.py, tox.ini
Loki was missing workload traces. 
Configure Loki to send workload traces using environment variables.
Implemented workload traces with an assumption of the split to charm and workload traces, as descibed here: https://discourse.charmhub.io/t/cos-endpoint-split-into-charm-tracing-and-workload-tracing/15978
See that the integration tests pass, or run the following bundle:
```
applications:
loki:
charm: local:loki-k8s-0
base: ubuntu@20.04/stable
scale: 1
constraints: arch=amd64
storage:
active-index-directory: kubernetes,1,1024M
loki-chunks: kubernetes,1,1024M
trust: true
minio:
charm: minio
channel: latest/edge
revision: 383
base: ubuntu@20.04/stable
resources:
oci-image: 545
scale: 1
options:
access-key: accesskey
secret-key: secretkey
constraints: arch=amd64
storage: …
```
=> Workload tracing

lib/charms/grafana_k8s/v0/grafana_source.py, metadata.yaml, requirements.txt, src/charm.py, tests/integration/helpers.py, tests/interface/conftest.py, tests/interface/test_grafana_datasource_exchange.py, tests/interface/test_grafana_source.py, tests/scenario/conftest.py, tests/scenario/test_datasource_exchange.py, tox.ini
Add a `send-datasource` endpoint to exchange datasource UIDs with other COS components.
TODO:
1. Deploy Tempo HA
2. Deploy `grafana-k8s`
3. Deploy `loki-k8s` from this branch
4. Integrate `tempo` and `grafana` over `grafana_datasource`
5. Integrate `loki` and `grafana` over `grafana_datasource`
6. Integrate `loki` and `tempo` over `grafana_datasource_exchange`
7. `jhack show-relation loki tempo` and observe the datasource UID of `loki` shared to `tempo`
=> Implement `grafana_datasource_exchange`

charmcraft.yaml, lib/charms/loki_k8s/v0/loki_push_api.py
Needed for the following PR: https://github.com/canonical/grafana-agent-operator/pull/231
More info on the CIS hardening rule can be found here[^1].
Use `path.chmod(0o775)` in order to comply wit the CIS Hardening rules.
[^1]: https://github.com/canonical/grafana-agent-operator/issues/208
=> fix: update cos-tool permissions to adhere to cis hardening rules

lib/charms/loki_k8s/v1/loki_push_api.py
Partially addresses https://github.com/canonical/grafana-agent-operator/issues/154
Allow charm authors to pass `forward_alert_rules=False` to both `LokiPushApiConsumer` and `LogForwarder` (pebble log forwarding).
When the flag is `True`, the alert rules information is simply not put in relation data.
Pack and deploy both this charm and grafana-agent from https://github.com/canonical/grafana-agent-operator/pull/252 , and test the new config option.
=> feat: add support for disabling alert rules forwarding

lib/charms/loki_k8s/v1/loki_push_api.py
Make the reloading alerts method public which is relevant in:
- https://github.com/canonical/opentelemetry-collector-k8s-operator/pull/7
This is done in [prometheus_remote_write with a reload_alerts method](https://github.com/canonical/prometheus-k8s-operator/blob/e09913477484f9ca006171ed949a9702bec3251e/lib/charms/prometheus_k8s/v1/prometheus_remote_write.py#L509) so this PR mirrors this functionality.
=> feat: make reloading alerts public

lib/charms/grafana_k8s/v0/grafana_source.py, src/charm.py, src/config_builder.py, tests/scenario/test_grafana_source.py
Loki needs to know the Grafana base URL for its `ruler` config which may have an ingress. This is needed to correctly render the Source button URL to Grafana when Loki alert rules are firing:
Is this relation the best way to give Loki the ingress URL from Grafana? It makes sense since this scenario requires the `grafana-source` relation, otherwise Loki logs won't make it to Grafana and this scenario won't be possible.
- https://github.com/canonical/alertmanager-k8s-operator/issues/293
- https://github.com/canonical/grafana-k8s-operator/pull/398
- https://grafana.com/docs/loki/latest/configure/#ruler
1. Create an always firing Loki alert rule in the [Zinc charm](https://github.com/jnsgruk/zinc-k8s-operator):
```yaml
alert: HostHighLogErrorRate
expr: …
```
=> feat: add grafana_base_url to Grafana source

terraform/README.md, terraform/main.tf, terraform/outputs.tf, terraform/variables.tf, terraform/versions.tf
There is currently no terraform module available for deploying Loki in the context of COS Lite.
Add a terraform module
- Clone repo
- `terraform init`
- `terraform apply -var="model_name=<MODEL_NAME>"`
Add terraform module for COS Lite flavor of Loki
=> feat(terraform): add terraform module

lib/charms/catalogue_k8s/v1/catalogue.py, lib/charms/tls_certificates_interface/v4/tls_certificates.py, src/charm.py
A [recent PR in Catalogue](https://github.com/canonical/catalogue-k8s-operator/pull/184) added functionality to the Catalogue library for Catalogue Items to provide links to their API docs and API endpoints. We need to add these fields when Mimir creates its Catalogue Items.
In tandem with PRs in:
- [Prometheus](https://github.com/canonical/prometheus-k8s-operator/pull/726)
- [Mimir Coordinator](https://github.com/canonical/mimir-coordinator-k8s-operator/pull/177)
- [Loki Coordinator](https://github.com/canonical/loki-coordinator-k8s-operator/pull/88)
- [Grafana](https://github.com/canonical/grafana-k8s-operator/pull/451)
This PR links to the upstream [HTTP API docs for Loki](https://grafana.com/docs/loki/latest/reference/loki-http-api/). It also lists some of the more commonly accessed …
=> chore: add api endpoints and docs to catalogue item
